version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flight-db
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build: ./Backend
    container_name: flight-backend
    working_dir: /app
    volumes:
      - ./Backend:/app
    ports:
      - "5002:5002"
    command: npm run dev
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: flights
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
