version: '3.8'
services:
  db:
    image: postgres:15
    container_name: flight-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: flight_booking
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
